version: '3.2'
services:
  web:
    build: .
    entrypoint: npm run dev
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - "80:80"
  cypress:
    image: cypress
    container_name: cypress
    depends_on:
      - web
    environment:
      - CYPRESS_baseUrl=http://web:80
    working_dir: /CypressGitDemo
    volumes:
      - ./:/CypressGitDemo
